longtowide: column and row variables must differ
Should fix confusion on the part of the user.

Also, _might_ fix this error on production that I've been unable to
reproduce (maybe because of a different pandas version on my dev
machine?):

Exception in reshape.render
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3020, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 161, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1296, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1304, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'police_district'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/server/models/loaded_module.py", line 158, in render
    out = self.render_impl(table, params, **kwargs)
  File "/tmp/minio_downloadyzybl29t", line 44, in render
    table.set_index(keys + [varcol], inplace=True, drop=True)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 4017, in set_index
    del frame[c]
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 2833, in __delitem__
    self._data.delete(key)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/internals.py", line 4182, in delete
    indexer = self.items.get_loc(item)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3022, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 161, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1296, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1304, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'police_district'